"""
add_to_working_idea_database.py
================================
Place this file inside your database/ folder.

Creates and manages a local SQLite database (working_ideas.db) with two tables:
  - working_ideas          : Ideas selected for active development via "Develop Now"
  - potential_future_ideas : Ideas saved for later via "Save for Later"
"""

import sqlite3
from pathlib import Path
from datetime import datetime

# All tables live in the shared project database
DB_PATH = Path(__file__).resolve().parents[2] / "data" / "pov_cocktail.db"


def init_db():
    """Create tables if they don't already exist."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS working_ideas (
            id           INTEGER PRIMARY KEY ,
            protocol_id  INTEGER,
            title        TEXT,
            cocktail     TEXT,
            idea_text    TEXT,
            summary      TEXT,
            created_at   TEXT
        )
    """)

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS potential_future_ideas (
            id           INTEGER PRIMARY KEY ,
            protocol_id  INTEGER,
            title        TEXT,
            cocktail     TEXT,
            idea_text    TEXT,
            summary      TEXT,
            created_at   TEXT
        )
    """)

    conn.commit()
    conn.close()


def add_to_working_idea_database(protocol_id, title, cocktail, idea_text, summary=""):
    """
    Save an idea to the working_ideas table for active development.

    Args:
        protocol_id (int): The upcoming protocol number for this idea.
        title (str):       The video title generated by the Creative Strategist.
        cocktail (str):    The target cocktail / subject of the video.
        idea_text (str):   Full idea body text as returned by Gemini.
        summary (str):     Short summary or hook line extracted from the idea.

    Returns:
        int: The row ID of the newly inserted record.
    """
    init_db()
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        """
        INSERT INTO working_ideas (protocol_id, title, cocktail, idea_text, summary, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (protocol_id, title, cocktail, idea_text, summary, datetime.now().isoformat())
    )
    row_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return row_id


def add_to_future_ideas_database(protocol_id, title, cocktail, idea_text, summary=""):
    """
    Save an idea to the potential_future_ideas table for later reference.

    Args:
        protocol_id (int): The upcoming protocol number at time of saving.
        title (str):       The video title generated by the Creative Strategist.
        cocktail (str):    The target cocktail / subject of the video.
        idea_text (str):   Full idea body text as returned by Gemini.
        summary (str):     Short summary or hook line extracted from the idea.

    Returns:
        int: The row ID of the newly inserted record.
    """
    init_db()
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(
        """
        INSERT INTO potential_future_ideas (protocol_id, title, cocktail, idea_text, summary, created_at)
        VALUES (?, ?, ?, ?, ?, ?)
        """,
        (protocol_id, title, cocktail, idea_text, summary, datetime.now().isoformat())
    )
    row_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return row_id


def get_latest_working_idea():
    """Return the most recently saved working idea as a dict, or None."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM working_ideas ORDER BY created_at DESC LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return dict(row) if row else None


def get_all_working_ideas():
    """Return all working ideas as a list of dicts (newest first)."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM working_ideas ORDER BY created_at DESC")
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return rows


def get_all_future_ideas():
    """Return all future/saved ideas as a list of dicts (newest first)."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM potential_future_ideas ORDER BY created_at DESC")
    rows = [dict(r) for r in cursor.fetchall()]
    conn.close()
    return rows